- src/MainView.vala
> Add a placeholder for an empty list

- src/Services/Manager.vala
Checks if the schema is present before making the Settings object. 
Also removes an unused function which is now only used in the indicator
fixes #17
> Prevent crash if indicator is not present

- README.md
- src/CMakeLists.txt
- src/MainView.vala
- src/Services/Manager.vala
> Rewrite MainView as a Granite.SimpleSettingsPage

- src/DeviceRow.vala
Fixes #32 
Also removes link for wacom settings that don't exist
> Remove link for sharing settings

- src/MainView.vala
Tie the spinner active state to the adapter's discovering property
> Make spinner match discovering state

- src/MainView.vala
> Sort devices with names above devices without

- src/MainView.vala
because it's duplicate information
> Remove placeholder icon

- src/DeviceRow.vala
> DeviceRow: Remove badges for unpaired devices

- src/MainView.vala
Fixes #62 
don't merge this before we get an icons release with https://github.com/elementary/icons/pull/711 or we'll get a gross GNOME fallback icon
> MainView: Use disabled icon when disabled

- data/io.elementary.switchboard.bluetooth.appdata.xml.in
- data/meson.build
> Rename Appdata to use the right RDNN

- src/MainView.vala
- src/Plug.vala
- src/Services/Manager.vala
> Fix discovery/discoverable on open

- data/io.elementary.switchboard.bluetooth.appdata.xml.in
Does not include a release tag so we can get translations
> Add Release info for 2.3.0

- src/DeviceRow.vala
Just saw it and thought I'd hop in and fix it.
> Fixed typo in "Unable to Connnect"

- data/io.elementary.switchboard.bluetooth.appdata.xml.in
For better display in Feedback and AppCenter
> AppData: Add "Settings" to name

- src/Services/Manager.vala
Followup fixes to #132 and https://github.com/elementary/switchboard/issues/180
> Fix crash when no bluetooth available

- src/MainView.vala
> Use OverlayBar instead of ActionBar

- src/MainView.vala
Maybe this was a workaround for something at some point?
> MainView: fix bottom margin

- data/io.elementary.switchboard.bluetooth.appdata.xml.in
- meson.build
I've confirmed that this builds and works correctly on Hera
> Release 2.3.4

- src/DeviceRow.vala
i tried pairing with bluetooth audio device and connected after pairing.
please correct it if it's not right.
https://github.com/elementary/switchboard-plug-bluetooth/issues/48
> Connect after paired

- src/DeviceRow.vala
Breaking some simple stuff out of #143 to make it easier to review.
> Fix compiler warnings

- src/Plug.vala
- src/Services/Manager.vala
> Inhibit closing until discovery stopped

- .github/workflows/githubci.yml
- README.md
- src/DeviceRow.vala
- src/MainView.vala
- src/PairDialog.vala
- src/Plug.vala
- src/meson.build
> Port to Gtk4

- src/Services/Manager.vala
Try to get bluetooth settings from the Daemon first and fallback to panel when it's not available
> Manager: get settings from Daemon

- debian/control
goes with https://github.com/elementary/switchboard-plug-bluetooth/pull/236
depends on:
> add bluetooth daemon dep

- src/DeviceRow.vala
Fixes screen reader reading out the markup
> DeviceRow: use CSS for small label

- src/DeviceRow.vala
- src/MainView.vala
Allows activating the row action with a double-click or by pressing enter
> DeviceRow: connect to activate
